// Mocks generated by Mockito 5.4.6 from annotations
// in onepanelapp_app/test/features/files/widgets/path_selector_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:onepanelapp_app/data/models/file_models.dart' as _i3;
import 'package:onepanelapp_app/features/files/files_provider.dart' as _i4;
import 'package:onepanelapp_app/features/files/models/models.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFilesData_0 extends _i1.SmartFake implements _i2.FilesData {
  _FakeFilesData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileSizeInfo_1 extends _i1.SmartFake implements _i3.FileSizeInfo {
  _FakeFileSizeInfo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileBatchCheckResult_2 extends _i1.SmartFake
    implements _i3.FileBatchCheckResult {
  _FakeFileBatchCheckResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileSearchResult_3 extends _i1.SmartFake
    implements _i3.FileSearchResult {
  _FakeFileSearchResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileUserGroupResponse_4 extends _i1.SmartFake
    implements _i3.FileUserGroupResponse {
  _FakeFileUserGroupResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileProperties_5 extends _i1.SmartFake
    implements _i3.FileProperties {
  _FakeFileProperties_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FilesProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilesProvider extends _i1.Mock implements _i4.FilesProvider {
  MockFilesProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FilesData get data => (super.noSuchMethod(
        Invocation.getter(#data),
        returnValue: _FakeFilesData_0(
          this,
          Invocation.getter(#data),
        ),
      ) as _i2.FilesData);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> loadServer() => (super.noSuchMethod(
        Invocation.method(
          #loadServer,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.FileInfo>> fetchFiles(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchFiles,
          [path],
        ),
        returnValue: _i5.Future<List<_i3.FileInfo>>.value(<_i3.FileInfo>[]),
      ) as _i5.Future<List<_i3.FileInfo>>);

  @override
  _i5.Future<void> loadFiles({String? path}) => (super.noSuchMethod(
        Invocation.method(
          #loadFiles,
          [],
          {#path: path},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadMountInfo() => (super.noSuchMethod(
        Invocation.method(
          #loadMountInfo,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadRecycleBinStatus() => (super.noSuchMethod(
        Invocation.method(
          #loadRecycleBinStatus,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.RecycleBinItem>> loadRecycleBinFiles({
    int? page = 1,
    int? pageSize = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadRecycleBinFiles,
          [],
          {
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue:
            _i5.Future<List<_i3.RecycleBinItem>>.value(<_i3.RecycleBinItem>[]),
      ) as _i5.Future<List<_i3.RecycleBinItem>>);

  @override
  _i5.Future<void> restoreFile(_i3.RecycleBinItem? file) => (super.noSuchMethod(
        Invocation.method(
          #restoreFile,
          [file],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> restoreFiles(List<_i3.RecycleBinItem>? files) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreFiles,
          [files],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deletePermanently(_i3.RecycleBinItem? file) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePermanently,
          [file],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deletePermanentlyFiles(List<_i3.RecycleBinItem>? files) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePermanentlyFiles,
          [files],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearRecycleBin() => (super.noSuchMethod(
        Invocation.method(
          #clearRecycleBin,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void onServerChanged() => super.noSuchMethod(
        Invocation.method(
          #onServerChanged,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> navigateTo(String? path) => (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [path],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> navigateUp() => (super.noSuchMethod(
        Invocation.method(
          #navigateUp,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void setSearchQuery(String? query) => super.noSuchMethod(
        Invocation.method(
          #setSearchQuery,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSorting(
    String? sortBy,
    String? sortOrder,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setSorting,
          [
            sortBy,
            sortOrder,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleSelection(String? path) => super.noSuchMethod(
        Invocation.method(
          #toggleSelection,
          [path],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectAll() => super.noSuchMethod(
        Invocation.method(
          #selectAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearSelection() => super.noSuchMethod(
        Invocation.method(
          #clearSelection,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> createDirectory(String? name) => (super.noSuchMethod(
        Invocation.method(
          #createDirectory,
          [name],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> createFile(
    String? name, {
    String? content,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFile,
          [name],
          {#content: content},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> uploadFiles(List<String>? filePaths) => (super.noSuchMethod(
        Invocation.method(
          #uploadFiles,
          [filePaths],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteSelected() => (super.noSuchMethod(
        Invocation.method(
          #deleteSelected,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteFile(String? path) => (super.noSuchMethod(
        Invocation.method(
          #deleteFile,
          [path],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> renameFile(
    String? oldPath,
    String? newName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameFile,
          [
            oldPath,
            newName,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> moveSelected(String? targetPath) => (super.noSuchMethod(
        Invocation.method(
          #moveSelected,
          [targetPath],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> copySelected(String? targetPath) => (super.noSuchMethod(
        Invocation.method(
          #copySelected,
          [targetPath],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> moveFile(
    String? sourcePath,
    String? targetPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveFile,
          [
            sourcePath,
            targetPath,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> copyFile(
    String? sourcePath,
    String? targetPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyFile,
          [
            sourcePath,
            targetPath,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> getFileContent(String? path) => (super.noSuchMethod(
        Invocation.method(
          #getFileContent,
          [path],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getFileContent,
            [path],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> saveFileContent(
    String? path,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFileContent,
          [
            path,
            content,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> compressSelected(
    String? name,
    String? type, {
    String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #compressSelected,
          [
            name,
            type,
          ],
          {#secret: secret},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> compressFiles(
    List<String>? files,
    String? dst,
    String? name,
    String? type, {
    String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #compressFiles,
          [
            files,
            dst,
            name,
            type,
          ],
          {#secret: secret},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> extractFile(
    String? path,
    String? dst,
    String? type, {
    String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractFile,
          [
            path,
            dst,
            type,
          ],
          {#secret: secret},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.FileSizeInfo> getFileSize(String? path) => (super.noSuchMethod(
        Invocation.method(
          #getFileSize,
          [path],
        ),
        returnValue: _i5.Future<_i3.FileSizeInfo>.value(_FakeFileSizeInfo_1(
          this,
          Invocation.method(
            #getFileSize,
            [path],
          ),
        )),
      ) as _i5.Future<_i3.FileSizeInfo>);

  @override
  _i5.Future<void> loadFavorites() => (super.noSuchMethod(
        Invocation.method(
          #loadFavorites,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addToFavorites(_i3.FileInfo? file) => (super.noSuchMethod(
        Invocation.method(
          #addToFavorites,
          [file],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeFromFavorites(String? path) => (super.noSuchMethod(
        Invocation.method(
          #removeFromFavorites,
          [path],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> toggleFavorite(_i3.FileInfo? file) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [file],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> wgetDownload({
    required String? url,
    required String? name,
    bool? ignoreCertificate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #wgetDownload,
          [],
          {
            #url: url,
            #name: name,
            #ignoreCertificate: ignoreCertificate,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void clearWgetStatus() => super.noSuchMethod(
        Invocation.method(
          #clearWgetStatus,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<List<_i3.FileInfo>> searchUploadedFiles({
    int? page = 1,
    int? pageSize = 20,
    String? search,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchUploadedFiles,
          [],
          {
            #page: page,
            #pageSize: pageSize,
            #search: search,
          },
        ),
        returnValue: _i5.Future<List<_i3.FileInfo>>.value(<_i3.FileInfo>[]),
      ) as _i5.Future<List<_i3.FileInfo>>);

  @override
  _i5.Future<void> batchChangeFileRole({
    required List<String>? paths,
    int? mode,
    String? user,
    String? group,
    bool? sub,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchChangeFileRole,
          [],
          {
            #paths: paths,
            #mode: mode,
            #user: user,
            #group: group,
            #sub: sub,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.FileMountInfo>> getMountInfo() => (super.noSuchMethod(
        Invocation.method(
          #getMountInfo,
          [],
        ),
        returnValue:
            _i5.Future<List<_i3.FileMountInfo>>.value(<_i3.FileMountInfo>[]),
      ) as _i5.Future<List<_i3.FileMountInfo>>);

  @override
  _i5.Future<_i3.FileBatchCheckResult> batchCheckFiles(List<String>? paths) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchCheckFiles,
          [paths],
        ),
        returnValue: _i5.Future<_i3.FileBatchCheckResult>.value(
            _FakeFileBatchCheckResult_2(
          this,
          Invocation.method(
            #batchCheckFiles,
            [paths],
          ),
        )),
      ) as _i5.Future<_i3.FileBatchCheckResult>);

  @override
  _i5.Future<_i3.FileSearchResult> searchInFiles({
    required String? pattern,
    bool? caseSensitive,
    bool? wholeWord,
    bool? regex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchInFiles,
          [],
          {
            #pattern: pattern,
            #caseSensitive: caseSensitive,
            #wholeWord: wholeWord,
            #regex: regex,
          },
        ),
        returnValue:
            _i5.Future<_i3.FileSearchResult>.value(_FakeFileSearchResult_3(
          this,
          Invocation.method(
            #searchInFiles,
            [],
            {
              #pattern: pattern,
              #caseSensitive: caseSensitive,
              #wholeWord: wholeWord,
              #regex: regex,
            },
          ),
        )),
      ) as _i5.Future<_i3.FileSearchResult>);

  @override
  _i5.Future<void> changeFileMode(
    String? path,
    int? mode, {
    bool? sub,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeFileMode,
          [
            path,
            mode,
          ],
          {#sub: sub},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> changeFileOwner(
    String? path,
    String? user,
    String? group, {
    bool? sub,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeFileOwner,
          [
            path,
            user,
            group,
          ],
          {#sub: sub},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.FileUserGroupResponse> getUserGroup() => (super.noSuchMethod(
        Invocation.method(
          #getUserGroup,
          [],
        ),
        returnValue: _i5.Future<_i3.FileUserGroupResponse>.value(
            _FakeFileUserGroupResponse_4(
          this,
          Invocation.method(
            #getUserGroup,
            [],
          ),
        )),
      ) as _i5.Future<_i3.FileUserGroupResponse>);

  @override
  _i5.Future<String?> downloadFile(_i3.FileInfo? file) => (super.noSuchMethod(
        Invocation.method(
          #downloadFile,
          [file],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<_i3.FileProperties> getFileProperties(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFileProperties,
          [path],
        ),
        returnValue: _i5.Future<_i3.FileProperties>.value(_FakeFileProperties_5(
          this,
          Invocation.method(
            #getFileProperties,
            [path],
          ),
        )),
      ) as _i5.Future<_i3.FileProperties>);

  @override
  _i5.Future<void> createFileLink({
    required String? sourcePath,
    required String? linkPath,
    required String? linkType,
    bool? overwrite,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFileLink,
          [],
          {
            #sourcePath: sourcePath,
            #linkPath: linkPath,
            #linkType: linkType,
            #overwrite: overwrite,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isStoragePermissionPermanentlyDenied() =>
      (super.noSuchMethod(
        Invocation.method(
          #isStoragePermissionPermanentlyDenied,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  void cancelDownload() => super.noSuchMethod(
        Invocation.method(
          #cancelDownload,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
