// Mocks generated by Mockito 5.4.6 from annotations
// in onepanelapp_app/test/features/files/files_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:onepanelapp_app/core/config/api_config.dart' as _i5;
import 'package:onepanelapp_app/data/models/file_models.dart' as _i2;
import 'package:onepanelapp_app/features/files/files_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFileSearchResponse_0 extends _i1.SmartFake
    implements _i2.FileSearchResponse {
  _FakeFileSearchResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileCheckResult_1 extends _i1.SmartFake
    implements _i2.FileCheckResult {
  _FakeFileCheckResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileTree_2 extends _i1.SmartFake implements _i2.FileTree {
  _FakeFileTree_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileSizeInfo_3 extends _i1.SmartFake implements _i2.FileSizeInfo {
  _FakeFileSizeInfo_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileWgetResult_4 extends _i1.SmartFake
    implements _i2.FileWgetResult {
  _FakeFileWgetResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileDepthSizeInfo_5 extends _i1.SmartFake
    implements _i2.FileDepthSizeInfo {
  _FakeFileDepthSizeInfo_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileUserGroupResponse_6 extends _i1.SmartFake
    implements _i2.FileUserGroupResponse {
  _FakeFileUserGroupResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileBatchCheckResult_7 extends _i1.SmartFake
    implements _i2.FileBatchCheckResult {
  _FakeFileBatchCheckResult_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FilesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilesService extends _i1.Mock implements _i3.FilesService {
  MockFilesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i5.ApiConfig?> getCurrentServer() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentServer,
          [],
        ),
        returnValue: _i4.Future<_i5.ApiConfig?>.value(),
      ) as _i4.Future<_i5.ApiConfig?>);

  @override
  _i4.Future<_i2.FileSearchResponse> searchFiles({
    required String? path,
    String? search,
    int? page = 1,
    int? pageSize = 100,
    bool? expand,
    String? sortBy,
    String? sortOrder,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFiles,
          [],
          {
            #path: path,
            #search: search,
            #page: page,
            #pageSize: pageSize,
            #expand: expand,
            #sortBy: sortBy,
            #sortOrder: sortOrder,
          },
        ),
        returnValue:
            _i4.Future<_i2.FileSearchResponse>.value(_FakeFileSearchResponse_0(
          this,
          Invocation.method(
            #searchFiles,
            [],
            {
              #path: path,
              #search: search,
              #page: page,
              #pageSize: pageSize,
              #expand: expand,
              #sortBy: sortBy,
              #sortOrder: sortOrder,
            },
          ),
        )),
      ) as _i4.Future<_i2.FileSearchResponse>);

  @override
  _i4.Future<List<_i2.FileInfo>> getFiles({
    required String? path,
    String? search,
    int? page = 1,
    int? pageSize = 100,
    bool? expand = true,
    String? sortBy,
    String? sortOrder,
    bool? showHidden,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFiles,
          [],
          {
            #path: path,
            #search: search,
            #page: page,
            #pageSize: pageSize,
            #expand: expand,
            #sortBy: sortBy,
            #sortOrder: sortOrder,
            #showHidden: showHidden,
          },
        ),
        returnValue: _i4.Future<List<_i2.FileInfo>>.value(<_i2.FileInfo>[]),
      ) as _i4.Future<List<_i2.FileInfo>>);

  @override
  _i4.Future<void> createDirectory(String? path) => (super.noSuchMethod(
        Invocation.method(
          #createDirectory,
          [path],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createFile(
    String? path, {
    String? content,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFile,
          [path],
          {#content: content},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteFiles(
    List<String>? paths, {
    bool? force,
    bool? isDir,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFiles,
          [paths],
          {
            #force: force,
            #isDir: isDir,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> renameFile(
    String? oldPath,
    String? newPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameFile,
          [
            oldPath,
            newPath,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> moveFiles(
    List<String>? paths,
    String? targetPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveFiles,
          [
            paths,
            targetPath,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> copyFiles(
    List<String>? paths,
    String? targetPath, {
    String? newName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyFiles,
          [
            paths,
            targetPath,
          ],
          {#newName: newName},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> getFileContent(String? path) => (super.noSuchMethod(
        Invocation.method(
          #getFileContent,
          [path],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getFileContent,
            [path],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> updateFileContent(
    String? path,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFileContent,
          [
            path,
            content,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> compressFiles({
    required List<String>? files,
    required String? dst,
    required String? name,
    required String? type,
    String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #compressFiles,
          [],
          {
            #files: files,
            #dst: dst,
            #name: name,
            #type: type,
            #secret: secret,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> extractFile({
    required String? path,
    required String? dst,
    required String? type,
    String? secret,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractFile,
          [],
          {
            #path: path,
            #dst: dst,
            #type: type,
            #secret: secret,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> changeFileMode(
    String? path,
    int? mode, {
    bool? sub,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeFileMode,
          [
            path,
            mode,
          ],
          {#sub: sub},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> changeFileOwner(
    String? path,
    String? user,
    String? group, {
    bool? sub,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeFileOwner,
          [
            path,
            user,
            group,
          ],
          {#sub: sub},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> batchChangeFileRole({
    required List<String>? paths,
    int? mode,
    String? user,
    String? group,
    bool? sub,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchChangeFileRole,
          [],
          {
            #paths: paths,
            #mode: mode,
            #user: user,
            #group: group,
            #sub: sub,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.FileCheckResult> checkFile(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkFile,
          [path],
        ),
        returnValue:
            _i4.Future<_i2.FileCheckResult>.value(_FakeFileCheckResult_1(
          this,
          Invocation.method(
            #checkFile,
            [path],
          ),
        )),
      ) as _i4.Future<_i2.FileCheckResult>);

  @override
  _i4.Future<_i2.FileTree> getFileTree({
    required String? path,
    int? maxDepth,
    bool? includeFiles,
    bool? includeHidden,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFileTree,
          [],
          {
            #path: path,
            #maxDepth: maxDepth,
            #includeFiles: includeFiles,
            #includeHidden: includeHidden,
          },
        ),
        returnValue: _i4.Future<_i2.FileTree>.value(_FakeFileTree_2(
          this,
          Invocation.method(
            #getFileTree,
            [],
            {
              #path: path,
              #maxDepth: maxDepth,
              #includeFiles: includeFiles,
              #includeHidden: includeHidden,
            },
          ),
        )),
      ) as _i4.Future<_i2.FileTree>);

  @override
  _i4.Future<_i2.FileSizeInfo> getFileSize(
    String? path, {
    bool? recursive,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFileSize,
          [path],
          {#recursive: recursive},
        ),
        returnValue: _i4.Future<_i2.FileSizeInfo>.value(_FakeFileSizeInfo_3(
          this,
          Invocation.method(
            #getFileSize,
            [path],
            {#recursive: recursive},
          ),
        )),
      ) as _i4.Future<_i2.FileSizeInfo>);

  @override
  _i4.Future<void> favoriteFile(
    String? path, {
    String? name,
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #favoriteFile,
          [path],
          {
            #name: name,
            #description: description,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unfavoriteFile(String? path) => (super.noSuchMethod(
        Invocation.method(
          #unfavoriteFile,
          [path],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.FileInfo>> searchFavoriteFiles({
    required String? path,
    int? page = 1,
    int? pageSize = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFavoriteFiles,
          [],
          {
            #path: path,
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i4.Future<List<_i2.FileInfo>>.value(<_i2.FileInfo>[]),
      ) as _i4.Future<List<_i2.FileInfo>>);

  @override
  _i4.Future<String> getRecycleBinStatus() => (super.noSuchMethod(
        Invocation.method(
          #getRecycleBinStatus,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getRecycleBinStatus,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<List<_i2.FileInfo>> searchRecycleBin({
    required String? path,
    int? page = 1,
    int? pageSize = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRecycleBin,
          [],
          {
            #path: path,
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i4.Future<List<_i2.FileInfo>>.value(<_i2.FileInfo>[]),
      ) as _i4.Future<List<_i2.FileInfo>>);

  @override
  _i4.Future<void> clearRecycleBin() => (super.noSuchMethod(
        Invocation.method(
          #clearRecycleBin,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> restoreFile(_i2.RecycleBinReduceRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreFile,
          [request],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> restoreFiles(List<_i2.RecycleBinReduceRequest>? requests) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreFiles,
          [requests],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRecycleBinFiles(List<_i2.RecycleBinItem>? files) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRecycleBinFiles,
          [files],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.FileWgetResult> wgetDownload({
    required String? url,
    required String? path,
    required String? name,
    bool? ignoreCertificate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #wgetDownload,
          [],
          {
            #url: url,
            #path: path,
            #name: name,
            #ignoreCertificate: ignoreCertificate,
          },
        ),
        returnValue: _i4.Future<_i2.FileWgetResult>.value(_FakeFileWgetResult_4(
          this,
          Invocation.method(
            #wgetDownload,
            [],
            {
              #url: url,
              #path: path,
              #name: name,
              #ignoreCertificate: ignoreCertificate,
            },
          ),
        )),
      ) as _i4.Future<_i2.FileWgetResult>);

  @override
  _i4.Future<List<_i2.FileInfo>> searchUploadedFiles({
    int? page = 1,
    int? pageSize = 20,
    String? search,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchUploadedFiles,
          [],
          {
            #page: page,
            #pageSize: pageSize,
            #search: search,
          },
        ),
        returnValue: _i4.Future<List<_i2.FileInfo>>.value(<_i2.FileInfo>[]),
      ) as _i4.Future<List<_i2.FileInfo>>);

  @override
  _i4.Future<_i2.FileDepthSizeInfo> getDepthSize(List<String>? paths) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDepthSize,
          [paths],
        ),
        returnValue:
            _i4.Future<_i2.FileDepthSizeInfo>.value(_FakeFileDepthSizeInfo_5(
          this,
          Invocation.method(
            #getDepthSize,
            [paths],
          ),
        )),
      ) as _i4.Future<_i2.FileDepthSizeInfo>);

  @override
  _i4.Future<List<_i2.FileMountInfo>> getMountInfo() => (super.noSuchMethod(
        Invocation.method(
          #getMountInfo,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.FileMountInfo>>.value(<_i2.FileMountInfo>[]),
      ) as _i4.Future<List<_i2.FileMountInfo>>);

  @override
  _i4.Future<void> createFileLink({
    required String? sourcePath,
    required String? linkPath,
    required String? linkType,
    bool? overwrite,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFileLink,
          [],
          {
            #sourcePath: sourcePath,
            #linkPath: linkPath,
            #linkType: linkType,
            #overwrite: overwrite,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> previewFile(
    String? path, {
    int? line,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #previewFile,
          [path],
          {
            #line: line,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #previewFile,
            [path],
            {
              #line: line,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i2.FileUserGroupResponse> getUserGroup() => (super.noSuchMethod(
        Invocation.method(
          #getUserGroup,
          [],
        ),
        returnValue: _i4.Future<_i2.FileUserGroupResponse>.value(
            _FakeFileUserGroupResponse_6(
          this,
          Invocation.method(
            #getUserGroup,
            [],
          ),
        )),
      ) as _i4.Future<_i2.FileUserGroupResponse>);

  @override
  _i4.Future<_i2.FileBatchCheckResult> batchCheckFiles(List<String>? paths) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchCheckFiles,
          [paths],
        ),
        returnValue: _i4.Future<_i2.FileBatchCheckResult>.value(
            _FakeFileBatchCheckResult_7(
          this,
          Invocation.method(
            #batchCheckFiles,
            [paths],
          ),
        )),
      ) as _i4.Future<_i2.FileBatchCheckResult>);

  @override
  _i4.Future<void> saveFile(
    String? path,
    String? content, {
    String? encoding,
    bool? createDir,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFile,
          [
            path,
            content,
          ],
          {
            #encoding: encoding,
            #createDir: createDir,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> readFile(
    String? path, {
    int? offset,
    int? length,
    String? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readFile,
          [path],
          {
            #offset: offset,
            #length: length,
            #encoding: encoding,
          },
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #readFile,
            [path],
            {
              #offset: offset,
              #length: length,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> downloadFile(
    String? path,
    String? savePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadFile,
          [
            path,
            savePath,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> downloadFileToDevice(
    String? filePath,
    String? fileName, {
    dynamic Function(
      int,
      int,
    )? onProgress,
    dynamic Function()? onCancel,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadFileToDevice,
          [
            filePath,
            fileName,
          ],
          {
            #onProgress: onProgress,
            #onCancel: onCancel,
          },
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #downloadFileToDevice,
            [
              filePath,
              fileName,
            ],
            {
              #onProgress: onProgress,
              #onCancel: onCancel,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  void cancelDownload() => super.noSuchMethod(
        Invocation.method(
          #cancelDownload,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<bool> checkAndRequestStoragePermission() => (super.noSuchMethod(
        Invocation.method(
          #checkAndRequestStoragePermission,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isStoragePermissionPermanentlyDenied() =>
      (super.noSuchMethod(
        Invocation.method(
          #isStoragePermissionPermanentlyDenied,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> uploadFile(
    String? path,
    dynamic file,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [
            path,
            file,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
